### ISSUE TITLE
Add language: Coffeescript

### ISSUE THREAD

**Issue by andrewhoyer** [andrewhoyer/leap-year#12]
[https://coffeescript.org/](https://coffeescript.org/)

**Comment by andrewhoyer** [comment]
Please see [CONTRIBUTING.md](https://github.com/andrewhoyer/leap-year/blob/main/CONTRIBUTING.md) for details.

**Comment by Suhas183** [comment]
Could you please assign this task to me?
My PR: https://github.com/andrewhoyer/leap-year/pull/30

**Comment by andrewhoyer** [comment]
I've assigned it to you, and will review your PR soon!

**Comment by Suhas183** [comment]
yess sure, waiting for the review :)

**Comment by andrewhoyer** [comment]
Thanks for adding Coffeescript!
