### ISSUE TITLE
Add language: C#

### ISSUE THREAD

**Issue by andrewhoyer** [andrewhoyer/leap-year#13]
Please see [CONTRIBUTING.md](https://github.com/andrewhoyer/leap-year/blob/main/CONTRIBUTING.md) for details on how to create a good PR for this project.

If you are going to work on this, please add a comment to avoid duplication of work.

**Comment by blindaks** [comment]
@andrewhoyer I would like to work on this issue. Please assign it to me.

**Comment by andrewhoyer** [comment]
Done! Thank you for participating!
