### ISSUE TITLE
Add language: Ruby

### ISSUE THREAD

**Issue by andrewhoyer** [andrewhoyer/leap-year#14]
Please see [CONTRIBUTING.md](https://github.com/andrewhoyer/leap-year/blob/main/CONTRIBUTING.md) for details on how to create a good PR for this project.

If you are going to work on this, please add a comment to avoid duplication of work.

**Comment by anupdsouza** [comment]
Hi @andrewhoyer, I'd like to work on this.

**Comment by andrewhoyer** [comment]
Hey @anupdsouza, it's all yours!
