### ISSUE TITLE
Add language: R

### ISSUE THREAD

**Issue by andrewhoyer** [andrewhoyer/leap-year#15]
Please see [CONTRIBUTING.md](https://github.com/andrewhoyer/leap-year/blob/main/CONTRIBUTING.md) for details on how to create a good PR for this project.

If you are going to work on this, please add a comment to avoid duplication of work.

**Comment by arya2004** [comment]
@andrewhoyer please assign this issue to me

**Comment by andrewhoyer** [comment]
Alright, it's all yours to develop!

**Comment by arya2004** [comment]
@andrewhoyer created the PR, please check

**Comment by andrewhoyer** [comment]
Thank you!
