### ISSUE TITLE
Add language: Kotlin

### ISSUE THREAD

**Issue by andrewhoyer** [andrewhoyer/leap-year#16]
Please see [CONTRIBUTING.md](https://github.com/andrewhoyer/leap-year/blob/main/CONTRIBUTING.md) for details on how to create a good PR for this project.

If you are going to work on this, please add a comment to avoid duplication of work.

**Comment by RohanGoparaju28** [comment]
Hi bro I am intrested in sharing on open source to your project

**Comment by RohanGoparaju28** [comment]
What is the problem

**Comment by realjoni17** [comment]
hi i want to solve this

**Comment by andrewhoyer** [comment]
Thanks for your contribution.
