### ISSUE TITLE
Add language: Dart

### ISSUE THREAD

**Issue by andrewhoyer** [andrewhoyer/leap-year#18]
https://dart.dev/

Please see [CONTRIBUTING.md](https://github.com/andrewhoyer/leap-year/blob/main/CONTRIBUTING.md) for details on how to create a good PR for this project.

If you are going to work on this, please add a comment to avoid duplication of work.

**Comment by ghost** [comment]
I would like to work on this.

**Comment by andrewhoyer** [comment]
Alright, thank you! I've assigned the issue to you.
