### ISSUE TITLE
Add language: Lua

### ISSUE THREAD

**Issue by andrewhoyer** [andrewhoyer/leap-year#19]
Please see [CONTRIBUTING.md](https://github.com/andrewhoyer/leap-year/blob/main/CONTRIBUTING.md) for details on how to create a good PR for this project.

If you are going to work on this, please add a comment to avoid duplication of work.

**Comment by sahuf2003** [comment]
@andrewhoyer I would like to work on this issue

**Comment by andrewhoyer** [comment]
@sahuf2003 I'm assigning it to you!

**Comment by andrewhoyer** [comment]
Thanks for your contribution to this repo!
