### ISSUE TITLE
Add language: Haskell

### ISSUE THREAD

**Issue by andrewhoyer** [andrewhoyer/leap-year#20]
Please see [CONTRIBUTING.md](https://github.com/andrewhoyer/leap-year/blob/main/CONTRIBUTING.md) for details on how to create a good PR for this project.

If you are going to work on this, please add a comment to avoid duplication of work.

**Comment by ajaykumar-br** [comment]
Hi @andrewhoyer , I would like to work on this, please assign it to me.

**Comment by andrewhoyer** [comment]
Hello! I've assigned this issue to you!

**Comment by ajaykumar-br** [comment]
Thank you, I have submitted a pull request, please review it 
Added Haskell Code #29

**Comment by ajaykumar-br** [comment]
> Hello! I've assigned this issue to you!

sorry to be bugging you, 
but I think you self-assigned it, unless I am mistaken.

**Comment by andrewhoyer** [comment]
Hey @ajaykumar-br. I assigned the PR to myself to review. This issue is assigned to you.

I've merged and closed the PR, and added the hacktoberfest-accepted label to it.
