### ISSUE TITLE
Add language: MSSQL

### ISSUE THREAD

**Issue by andrewhoyer** [andrewhoyer/leap-year#21]
This issue is to create an SQL statement for Microsoft SQL Server.

https://www.microsoft.com/en-ca/sql-server

**NOTE**: The solution should be placed inside the "SQL" folder. See the existing MySQL example as a guide.

Please see [CONTRIBUTING.md](https://github.com/andrewhoyer/leap-year/blob/main/CONTRIBUTING.md) for details on how to create a good PR for this project.

If you are going to work on this, please add a comment to avoid duplication of work.

**Comment by rohitmore07** [comment]
@andrewhoyer I would be really happy if you could assign this issue to me.

**Comment by andrewhoyer** [comment]
Hey @rohitmore07, I'm assigning this to you! Please be sure to take a look at how others in the SQL folder are set up and model yours after them.

**Comment by rohitmore07** [comment]
Please review my pull request when you get a chance. If there's anything that needs improvement or further clarification, feel free to let me know!

**Comment by andrewhoyer** [comment]
Thanks for your contribution.
