### ISSUE TITLE
Want to add leap Year in Assembly (emu-8086)

### ISSUE THREAD

**Issue by mehdi621-git** [andrewhoyer/leap-year#37]
Please assign me this under HacktoberFest 2024 #hacktoberFest

**Comment by andrewhoyer** [comment]
Hi @mehdi621-git. Alright, I will assign this Issue to you to work on. Note that we already have an Assembly entry, but I believe yours is for a different platform.

Please name your folder something like Aseembly-emu-8086 to describe the difference.

Also, please read the CONTRIBUTING file carefully and ensure you have all of the steps, including the two README files.

I will assign the proper Hacktoberfest labels.

**Comment by mehdi621-git** [comment]
Please merge this under HacktoberFest 2024

**Comment by andrewhoyer** [comment]
PR merged. Thank you for your contribution! I marked the PR hacktoberfest-accepted.
