### ISSUE TITLE
Add language : Prolog

### ISSUE THREAD

**Issue by MonilMehta** [andrewhoyer/leap-year#38]
Hi want to add the leap year program in prolog

**Comment by andrewhoyer** [comment]
Hey @MonilMehta. Alright, I'll assign this Issue to you. When you're ready, send a PR. Be sure to see the CONTRIBUTING file to make sure you've got all of the necessary steps, including two README files which are often overlooked.

**Comment by andrewhoyer** [comment]
Are you participating in Hacktoberfest? Let me know, and I will be sure to add the necessary labels.

**Comment by MonilMehta** [comment]
Hi there, yes I'm participating in Hacktoberfest.

Regards,
Monil Mehta

**Comment by MonilMehta** [comment]
I have added a PR, can you check?

**Comment by andrewhoyer** [comment]
Hi @MonilMehta. Thank you for your PR, and for following all of the contributing guidelines. It really makes things easy for maintainers when developers put in a little extra effort. 

I tagged the PR as hacktoberfest-accepted, so you should see it on your Hacktoberfest dashboard.
